name: GTA SA DC (Rentgen Serwera)

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Pobranie kodu
        uses: actions/checkout@v4

      - name: Kompilacja w Dockerze
        run: |
          docker run --rm -v ${{ github.workspace }}:/src -w /src nold360/kallistios-sdk /bin/bash -c "
            set -ex # Wypisuj kazda komende i przerywaj przy bledzie!
            ls -la
            make
            sh-elf-objcopy -R .stack -O binary my_game.elf main.bin
            scramble main.bin 1ST_READ.BIN
            cp /opt/mksdiso/src/makeip/ip.txt .
            makeip ip.txt IP.BIN
            genisoimage -V MOJA_GRA -G IP.BIN -joliet -rock -l -o mygame.iso 1ST_READ.BIN
            cdi4dc mygame.iso MojaGra_GTA.cdi -d
            ls -la
          "

      - name: Debug - Rentgen i naprawa uprawnien na Host
        run: |
          echo "=== Lista plikow przed naprawa ==="
          sudo ls -la ${{ github.workspace }}
          echo "=== Nadawanie pelnych uprawnien ==="
          sudo chmod -R 777 ${{ github.workspace }}
          echo "=== Ostateczna lista plikow ==="
          sudo find ${{ github.workspace }} -type f

      - name: Zapisanie WSZYSTKIEGO (Artifacts)
        uses: actions/upload-artifact@v4
        with:
          name: Dreamcast-Build
          path: .
          if-no-files-found: error
