name: GTA SA DC (Ostateczny Cios)

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Pobranie kodu
        uses: actions/checkout@v4

      - name: 1. Sprawdzenie plikow na Host
        run: ls -la

      - name: 2. Kompilacja w Dockerze
        run: |
          docker run --rm -v ${{ github.workspace }}:/src -w /src nold360/kallistios-sdk /bin/bash -c "
            set -e
            make
            sh-elf-objcopy -R .stack -O binary my_game.elf main.bin
            scramble main.bin 1ST_READ.BIN
            cp /opt/mksdiso/src/makeip/ip.txt .
            makeip ip.txt IP.BIN
            genisoimage -V MOJA_GRA -G IP.BIN -joliet -rock -l -o mygame.iso 1ST_READ.BIN
            cdi4dc mygame.iso MojaGra.cdi -d
            chmod 777 *
          "

      - name: 3. Zabicie Roota (Naprawa uprawnien na Host)
        run: |
          sudo chmod -R 777 ${{ github.workspace }}
          echo "=== Pliki po naprawie ==="
          ls -la

      - name: 4. Pobranie WSZYSTKIEGO (Artifacts)
        uses: actions/upload-artifact@v4
        with:
          name: Dreamcast-Full-ZIP
          path: .
